export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT = "LOGOUT"

export const LOADING_PICS = "LOADING_PICS"
export const DONE_LOADING_PICS = "DONE_LOADING_PICS"
export const FETCH_PICS = "FETCH_PICS"

// export const SAVE_PIC = "SAVE_PIC"